// Copyright 2021 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Proto definitions supporting the Chrome Root Store.
// This file should be manually kept in sync with the corresponding google3
// file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.22.3
// source: root_store.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Specifies a set of constraints, all of which that have values must be
// satisfied for the ConstraintSet to be satisfied.
type ConstraintSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The leaf certificate must have at least one valid SCT timestamp that is
	// not after the specified value, specified in seconds since the unix epoch.
	SctNotAfterSec *int64 `protobuf:"varint,1,opt,name=sct_not_after_sec,json=sctNotAfterSec,proto3,oneof" json:"sct_not_after_sec,omitempty"`
	// The leaf certificate must have at least one valid SCT timestamp and all
	// valid SCT timestamps must be after the specified value, specified in
	// seconds since the unix epoch.
	SctAllAfterSec *int64 `protobuf:"varint,2,opt,name=sct_all_after_sec,json=sctAllAfterSec,proto3,oneof" json:"sct_all_after_sec,omitempty"`
	// The browser version must be equal to or greater than the specified version.
	// Specified as a dotted version string, for example, "121.0.6167.160". A
	// partial version is also allowed, for example min_version="121" will match
	// any M-121 version or later.
	MinVersion *string `protobuf:"bytes,3,opt,name=min_version,json=minVersion,proto3,oneof" json:"min_version,omitempty"`
	// The browser version must be less than the specified version.
	// For example, max_version_exclusive="122" will match any M-121 or earlier
	// version, and will not match any M-122 version.
	MaxVersionExclusive *string `protobuf:"bytes,4,opt,name=max_version_exclusive,json=maxVersionExclusive,proto3,oneof" json:"max_version_exclusive,omitempty"`
}

func (x *ConstraintSet) Reset() {
	*x = ConstraintSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_root_store_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConstraintSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstraintSet) ProtoMessage() {}

func (x *ConstraintSet) ProtoReflect() protoreflect.Message {
	mi := &file_root_store_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstraintSet.ProtoReflect.Descriptor instead.
func (*ConstraintSet) Descriptor() ([]byte, []int) {
	return file_root_store_proto_rawDescGZIP(), []int{0}
}

func (x *ConstraintSet) GetSctNotAfterSec() int64 {
	if x != nil && x.SctNotAfterSec != nil {
		return *x.SctNotAfterSec
	}
	return 0
}

func (x *ConstraintSet) GetSctAllAfterSec() int64 {
	if x != nil && x.SctAllAfterSec != nil {
		return *x.SctAllAfterSec
	}
	return 0
}

func (x *ConstraintSet) GetMinVersion() string {
	if x != nil && x.MinVersion != nil {
		return *x.MinVersion
	}
	return ""
}

func (x *ConstraintSet) GetMaxVersionExclusive() string {
	if x != nil && x.MaxVersionExclusive != nil {
		return *x.MaxVersionExclusive
	}
	return ""
}

type TrustAnchor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The human-editable textproto version of the root store references roots in
	// a separate file by SHA-256 hash for convenience. It is converted to the DER
	// representation as part of the build process.
	//
	// Types that are assignable to Certificate:
	//
	//	*TrustAnchor_Der
	//	*TrustAnchor_Sha256Hex
	Certificate isTrustAnchor_Certificate `protobuf_oneof:"certificate"`
	// OID should be expressed as dotted-decimal text (e.g. "1.3.159.1.17.1")
	EvPolicyOids []string `protobuf:"bytes,3,rep,name=ev_policy_oids,json=evPolicyOids,proto3" json:"ev_policy_oids,omitempty"`
	// If not empty, the anchor is only trusted if at least one of the
	// ConstraintSets is satisfied.
	Constraints []*ConstraintSet `protobuf:"bytes,4,rep,name=constraints,proto3" json:"constraints,omitempty"`
	// Human-readable display name used to identify the certificate.
	DisplayName *string `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
}

func (x *TrustAnchor) Reset() {
	*x = TrustAnchor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_root_store_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrustAnchor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustAnchor) ProtoMessage() {}

func (x *TrustAnchor) ProtoReflect() protoreflect.Message {
	mi := &file_root_store_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustAnchor.ProtoReflect.Descriptor instead.
func (*TrustAnchor) Descriptor() ([]byte, []int) {
	return file_root_store_proto_rawDescGZIP(), []int{1}
}

func (m *TrustAnchor) GetCertificate() isTrustAnchor_Certificate {
	if m != nil {
		return m.Certificate
	}
	return nil
}

func (x *TrustAnchor) GetDer() []byte {
	if x, ok := x.GetCertificate().(*TrustAnchor_Der); ok {
		return x.Der
	}
	return nil
}

func (x *TrustAnchor) GetSha256Hex() string {
	if x, ok := x.GetCertificate().(*TrustAnchor_Sha256Hex); ok {
		return x.Sha256Hex
	}
	return ""
}

func (x *TrustAnchor) GetEvPolicyOids() []string {
	if x != nil {
		return x.EvPolicyOids
	}
	return nil
}

func (x *TrustAnchor) GetConstraints() []*ConstraintSet {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *TrustAnchor) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

type isTrustAnchor_Certificate interface {
	isTrustAnchor_Certificate()
}

type TrustAnchor_Der struct {
	Der []byte `protobuf:"bytes,1,opt,name=der,proto3,oneof"`
}

type TrustAnchor_Sha256Hex struct {
	Sha256Hex string `protobuf:"bytes,2,opt,name=sha256_hex,json=sha256Hex,proto3,oneof"`
}

func (*TrustAnchor_Der) isTrustAnchor_Certificate() {}

func (*TrustAnchor_Sha256Hex) isTrustAnchor_Certificate() {}

// Message storing a complete Chrome Root Store.
type RootStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrustAnchors []*TrustAnchor `protobuf:"bytes,1,rep,name=trust_anchors,json=trustAnchors,proto3" json:"trust_anchors,omitempty"`
	// Major version # of the Chrome Root Store. It is assumed that if
	// root_store_1.version_major > root_store_2.version_major, then root_store_1
	// is newer and should be preferred over root_store_2.
	VersionMajor int64 `protobuf:"varint,2,opt,name=version_major,json=versionMajor,proto3" json:"version_major,omitempty"`
}

func (x *RootStore) Reset() {
	*x = RootStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_root_store_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RootStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootStore) ProtoMessage() {}

func (x *RootStore) ProtoReflect() protoreflect.Message {
	mi := &file_root_store_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootStore.ProtoReflect.Descriptor instead.
func (*RootStore) Descriptor() ([]byte, []int) {
	return file_root_store_proto_rawDescGZIP(), []int{2}
}

func (x *RootStore) GetTrustAnchors() []*TrustAnchor {
	if x != nil {
		return x.TrustAnchors
	}
	return nil
}

func (x *RootStore) GetVersionMajor() int64 {
	if x != nil {
		return x.VersionMajor
	}
	return 0
}

var File_root_store_proto protoreflect.FileDescriptor

var file_root_store_proto_rawDesc = []byte{
	0x0a, 0x10, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x11, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x5f,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x22, 0xa4, 0x02, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x61, 0x69, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x12, 0x2e, 0x0a, 0x11, 0x73, 0x63, 0x74, 0x5f, 0x6e,
	0x6f, 0x74, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x00, 0x52, 0x0e, 0x73, 0x63, 0x74, 0x4e, 0x6f, 0x74, 0x41, 0x66, 0x74, 0x65,
	0x72, 0x53, 0x65, 0x63, 0x88, 0x01, 0x01, 0x12, 0x2e, 0x0a, 0x11, 0x73, 0x63, 0x74, 0x5f, 0x61,
	0x6c, 0x6c, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x48, 0x01, 0x52, 0x0e, 0x73, 0x63, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x66, 0x74, 0x65,
	0x72, 0x53, 0x65, 0x63, 0x88, 0x01, 0x01, 0x12, 0x24, 0x0a, 0x0b, 0x6d, 0x69, 0x6e, 0x5f, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0a,
	0x6d, 0x69, 0x6e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x37, 0x0a,
	0x15, 0x6d, 0x61, 0x78, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x65, 0x78, 0x63,
	0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x03, 0x52, 0x13,
	0x6d, 0x61, 0x78, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x73,
	0x69, 0x76, 0x65, 0x88, 0x01, 0x01, 0x42, 0x14, 0x0a, 0x12, 0x5f, 0x73, 0x63, 0x74, 0x5f, 0x6e,
	0x6f, 0x74, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x63, 0x42, 0x14, 0x0a, 0x12,
	0x5f, 0x73, 0x63, 0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x61, 0x66, 0x74, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x63, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x6d, 0x69, 0x6e, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x42, 0x18, 0x0a, 0x16, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x65, 0x78, 0x63, 0x6c, 0x75, 0x73, 0x69, 0x76, 0x65, 0x22, 0xf4, 0x01, 0x0a,
	0x0b, 0x54, 0x72, 0x75, 0x73, 0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x03,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x03, 0x64, 0x65, 0x72,
	0x12, 0x1f, 0x0a, 0x0a, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x5f, 0x68, 0x65, 0x78, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x48, 0x65,
	0x78, 0x12, 0x24, 0x0a, 0x0e, 0x65, 0x76, 0x5f, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x5f, 0x6f,
	0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x76, 0x50, 0x6f, 0x6c,
	0x69, 0x63, 0x79, 0x4f, 0x69, 0x64, 0x73, 0x12, 0x42, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x63,
	0x68, 0x72, 0x6f, 0x6d, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x53, 0x65, 0x74, 0x52, 0x0b,
	0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0c, 0x64,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x01, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x75, 0x0a, 0x09, 0x52, 0x6f, 0x6f, 0x74, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x12, 0x43, 0x0a, 0x0d, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x61, 0x6e, 0x63, 0x68, 0x6f, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x63, 0x68, 0x72, 0x6f, 0x6d, 0x65,
	0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x54, 0x72, 0x75, 0x73,
	0x74, 0x41, 0x6e, 0x63, 0x68, 0x6f, 0x72, 0x52, 0x0c, 0x74, 0x72, 0x75, 0x73, 0x74, 0x41, 0x6e,
	0x63, 0x68, 0x6f, 0x72, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x6d, 0x61, 0x6a, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x6a, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_root_store_proto_rawDescOnce sync.Once
	file_root_store_proto_rawDescData = file_root_store_proto_rawDesc
)

func file_root_store_proto_rawDescGZIP() []byte {
	file_root_store_proto_rawDescOnce.Do(func() {
		file_root_store_proto_rawDescData = protoimpl.X.CompressGZIP(file_root_store_proto_rawDescData)
	})
	return file_root_store_proto_rawDescData
}

var file_root_store_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_root_store_proto_goTypes = []interface{}{
	(*ConstraintSet)(nil), // 0: chrome_root_store.ConstraintSet
	(*TrustAnchor)(nil),   // 1: chrome_root_store.TrustAnchor
	(*RootStore)(nil),     // 2: chrome_root_store.RootStore
}
var file_root_store_proto_depIdxs = []int32{
	0, // 0: chrome_root_store.TrustAnchor.constraints:type_name -> chrome_root_store.ConstraintSet
	1, // 1: chrome_root_store.RootStore.trust_anchors:type_name -> chrome_root_store.TrustAnchor
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_root_store_proto_init() }
func file_root_store_proto_init() {
	if File_root_store_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_root_store_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConstraintSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_root_store_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrustAnchor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_root_store_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RootStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_root_store_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_root_store_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*TrustAnchor_Der)(nil),
		(*TrustAnchor_Sha256Hex)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_root_store_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_root_store_proto_goTypes,
		DependencyIndexes: file_root_store_proto_depIdxs,
		MessageInfos:      file_root_store_proto_msgTypes,
	}.Build()
	File_root_store_proto = out.File
	file_root_store_proto_rawDesc = nil
	file_root_store_proto_goTypes = nil
	file_root_store_proto_depIdxs = nil
}
