// Copyright 2021 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Proto definitions supporting the Chrome Root Store.
// This file should be manually kept in sync with the corresponding google3
// file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: root_store.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Specifies a set of constraints, all of which that have values must be
// satisfied for the ConstraintSet to be satisfied.
type ConstraintSet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The leaf certificate must have at least one valid SCT timestamp that is
	// not after the specified value, specified in seconds since the unix epoch.
	SctNotAfterSec *int64 `protobuf:"varint,1,opt,name=sct_not_after_sec,json=sctNotAfterSec,proto3,oneof" json:"sct_not_after_sec,omitempty"`
	// The leaf certificate must have at least one valid SCT timestamp and all
	// valid SCT timestamps must be after the specified value, specified in
	// seconds since the unix epoch.
	SctAllAfterSec *int64 `protobuf:"varint,2,opt,name=sct_all_after_sec,json=sctAllAfterSec,proto3,oneof" json:"sct_all_after_sec,omitempty"`
	// The browser version must be equal to or greater than the specified version.
	// Specified as a dotted version string, for example, "121.0.6167.160". A
	// partial version is also allowed, for example min_version="121" will match
	// any M-121 version or later.
	MinVersion *string `protobuf:"bytes,3,opt,name=min_version,json=minVersion,proto3,oneof" json:"min_version,omitempty"`
	// The browser version must be less than the specified version.
	// For example, max_version_exclusive="122" will match any M-121 or earlier
	// version, and will not match any M-122 version.
	MaxVersionExclusive *string `protobuf:"bytes,4,opt,name=max_version_exclusive,json=maxVersionExclusive,proto3,oneof" json:"max_version_exclusive,omitempty"`
	// All DNS names in the leaf certificate subjectAltNames must fall within the
	// subtrees defined by `permitted_dns_names`. The constraints are interpereted
	// as described in RFC 5280 section 4.2.1.10.
	PermittedDnsNames []string `protobuf:"bytes,5,rep,name=permitted_dns_names,json=permittedDnsNames,proto3" json:"permitted_dns_names,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConstraintSet) Reset() {
	*x = ConstraintSet{}
	mi := &file_root_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConstraintSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstraintSet) ProtoMessage() {}

func (x *ConstraintSet) ProtoReflect() protoreflect.Message {
	mi := &file_root_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstraintSet.ProtoReflect.Descriptor instead.
func (*ConstraintSet) Descriptor() ([]byte, []int) {
	return file_root_store_proto_rawDescGZIP(), []int{0}
}

func (x *ConstraintSet) GetSctNotAfterSec() int64 {
	if x != nil && x.SctNotAfterSec != nil {
		return *x.SctNotAfterSec
	}
	return 0
}

func (x *ConstraintSet) GetSctAllAfterSec() int64 {
	if x != nil && x.SctAllAfterSec != nil {
		return *x.SctAllAfterSec
	}
	return 0
}

func (x *ConstraintSet) GetMinVersion() string {
	if x != nil && x.MinVersion != nil {
		return *x.MinVersion
	}
	return ""
}

func (x *ConstraintSet) GetMaxVersionExclusive() string {
	if x != nil && x.MaxVersionExclusive != nil {
		return *x.MaxVersionExclusive
	}
	return ""
}

func (x *ConstraintSet) GetPermittedDnsNames() []string {
	if x != nil {
		return x.PermittedDnsNames
	}
	return nil
}

type TrustAnchor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The human-editable textproto version of the root store references roots in
	// a separate file by SHA-256 hash for convenience. It is converted to the DER
	// representation as part of the build process.
	//
	// Types that are valid to be assigned to Certificate:
	//
	//	*TrustAnchor_Der
	//	*TrustAnchor_Sha256Hex
	Certificate isTrustAnchor_Certificate `protobuf_oneof:"certificate"`
	// OID should be expressed as dotted-decimal text (e.g. "1.3.159.1.17.1")
	EvPolicyOids []string `protobuf:"bytes,3,rep,name=ev_policy_oids,json=evPolicyOids,proto3" json:"ev_policy_oids,omitempty"`
	// If not empty, the anchor is only trusted if at least one of the
	// ConstraintSets is satisfied.
	Constraints []*ConstraintSet `protobuf:"bytes,4,rep,name=constraints,proto3" json:"constraints,omitempty"`
	// Human-readable display name used to identify the certificate.
	DisplayName *string `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	// If true, indicates that this certificate is trusted to issue QWACs.
	Eutl *bool `protobuf:"varint,6,opt,name=eutl,proto3,oneof" json:"eutl,omitempty"`
	// When set to true, Chrome will enforce certificate expiry for this
	// TrustAnchor using the notBefore and notAfter from the corresponding
	// certificate.
	EnforceAnchorExpiry *bool `protobuf:"varint,8,opt,name=enforce_anchor_expiry,json=enforceAnchorExpiry,proto3,oneof" json:"enforce_anchor_expiry,omitempty"`
	// When set to true, Chrome will enforce X.509 constraints for this
	// TrustAnchor using the constraints expressed in the corresponding
	// certificate.
	EnforceAnchorConstraints *bool `protobuf:"varint,9,opt,name=enforce_anchor_constraints,json=enforceAnchorConstraints,proto3,oneof" json:"enforce_anchor_constraints,omitempty"`
	// If true, indicates that this certificate is a trust anchor for TLS
	// connections.
	TlsTrustAnchor *bool `protobuf:"varint,10,opt,name=tls_trust_anchor,json=tlsTrustAnchor,proto3,oneof" json:"tls_trust_anchor,omitempty"`
	// A unique identifier for a trust anchor, in binary representation.
	// Specified in
	// https://www.ietf.org/archive/id/draft-ietf-tls-trust-anchor-ids-00.html,
	// Trust Anchor IDs are represented as relative OID suffixes of the Private
	// Enterprise Number (PEN) OID prefix of "1.3.6.1.4.1.".
	TrustAnchorId []byte `protobuf:"bytes,11,opt,name=trust_anchor_id,json=trustAnchorId,proto3,oneof" json:"trust_anchor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrustAnchor) Reset() {
	*x = TrustAnchor{}
	mi := &file_root_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustAnchor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustAnchor) ProtoMessage() {}

func (x *TrustAnchor) ProtoReflect() protoreflect.Message {
	mi := &file_root_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustAnchor.ProtoReflect.Descriptor instead.
func (*TrustAnchor) Descriptor() ([]byte, []int) {
	return file_root_store_proto_rawDescGZIP(), []int{1}
}

func (x *TrustAnchor) GetCertificate() isTrustAnchor_Certificate {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *TrustAnchor) GetDer() []byte {
	if x != nil {
		if x, ok := x.Certificate.(*TrustAnchor_Der); ok {
			return x.Der
		}
	}
	return nil
}

func (x *TrustAnchor) GetSha256Hex() string {
	if x != nil {
		if x, ok := x.Certificate.(*TrustAnchor_Sha256Hex); ok {
			return x.Sha256Hex
		}
	}
	return ""
}

func (x *TrustAnchor) GetEvPolicyOids() []string {
	if x != nil {
		return x.EvPolicyOids
	}
	return nil
}

func (x *TrustAnchor) GetConstraints() []*ConstraintSet {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *TrustAnchor) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *TrustAnchor) GetEutl() bool {
	if x != nil && x.Eutl != nil {
		return *x.Eutl
	}
	return false
}

func (x *TrustAnchor) GetEnforceAnchorExpiry() bool {
	if x != nil && x.EnforceAnchorExpiry != nil {
		return *x.EnforceAnchorExpiry
	}
	return false
}

func (x *TrustAnchor) GetEnforceAnchorConstraints() bool {
	if x != nil && x.EnforceAnchorConstraints != nil {
		return *x.EnforceAnchorConstraints
	}
	return false
}

func (x *TrustAnchor) GetTlsTrustAnchor() bool {
	if x != nil && x.TlsTrustAnchor != nil {
		return *x.TlsTrustAnchor
	}
	return false
}

func (x *TrustAnchor) GetTrustAnchorId() []byte {
	if x != nil {
		return x.TrustAnchorId
	}
	return nil
}

type isTrustAnchor_Certificate interface {
	isTrustAnchor_Certificate()
}

type TrustAnchor_Der struct {
	Der []byte `protobuf:"bytes,1,opt,name=der,proto3,oneof"`
}

type TrustAnchor_Sha256Hex struct {
	Sha256Hex string `protobuf:"bytes,2,opt,name=sha256_hex,json=sha256Hex,proto3,oneof"`
}

func (*TrustAnchor_Der) isTrustAnchor_Certificate() {}

func (*TrustAnchor_Sha256Hex) isTrustAnchor_Certificate() {}

type MtcAnchor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The log id is a trust anchor id in binary representation.
	LogId []byte `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3,oneof" json:"log_id,omitempty"`
	// If not empty, the anchor is only trusted if at least one of the
	// ConstraintSets is satisfied.
	Constraints []*ConstraintSet `protobuf:"bytes,2,rep,name=constraints,proto3" json:"constraints,omitempty"`
	// If true, indicates that this MTC is a trust anchor for TLS connections.
	TlsTrustAnchor *bool `protobuf:"varint,3,opt,name=tls_trust_anchor,json=tlsTrustAnchor,proto3,oneof" json:"tls_trust_anchor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MtcAnchor) Reset() {
	*x = MtcAnchor{}
	mi := &file_root_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MtcAnchor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtcAnchor) ProtoMessage() {}

func (x *MtcAnchor) ProtoReflect() protoreflect.Message {
	mi := &file_root_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtcAnchor.ProtoReflect.Descriptor instead.
func (*MtcAnchor) Descriptor() ([]byte, []int) {
	return file_root_store_proto_rawDescGZIP(), []int{2}
}

func (x *MtcAnchor) GetLogId() []byte {
	if x != nil {
		return x.LogId
	}
	return nil
}

func (x *MtcAnchor) GetConstraints() []*ConstraintSet {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *MtcAnchor) GetTlsTrustAnchor() bool {
	if x != nil && x.TlsTrustAnchor != nil {
		return *x.TlsTrustAnchor
	}
	return false
}

// Message storing a complete Chrome Root Store.
type RootStore struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Certificates in this list are expected to have |tls_trust_anchor| unset,
	// because all |trust_anchors| are TLS trust anchors. This field exists as a
	// separate, TLS-trust-anchor-only list from |additional_certs| just for
	// historical reasons.
	TrustAnchors []*TrustAnchor `protobuf:"bytes,1,rep,name=trust_anchors,json=trustAnchors,proto3" json:"trust_anchors,omitempty"`
	// Major version # of the Chrome Root Store. It is assumed that if
	// root_store_1.version_major > root_store_2.version_major, then root_store_1
	// is newer and should be preferred over root_store_2.
	VersionMajor int64 `protobuf:"varint,2,opt,name=version_major,json=versionMajor,proto3" json:"version_major,omitempty"`
	// Additional certificates that are shipped as part of the Chrome Root Store
	// but convey different trust information than those in trust_anchors.
	AdditionalCerts []*TrustAnchor `protobuf:"bytes,3,rep,name=additional_certs,json=additionalCerts,proto3" json:"additional_certs,omitempty"`
	// Merkle Tree Certificate anchors. Like `additional_certs`, entries are not
	// trusted for any purpose unless explicitly specified in the MtcAnchor (for
	// example by setting `tls_trust_anchor=true`).
	MtcAnchors    []*MtcAnchor `protobuf:"bytes,4,rep,name=mtc_anchors,json=mtcAnchors,proto3" json:"mtc_anchors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RootStore) Reset() {
	*x = RootStore{}
	mi := &file_root_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RootStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RootStore) ProtoMessage() {}

func (x *RootStore) ProtoReflect() protoreflect.Message {
	mi := &file_root_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RootStore.ProtoReflect.Descriptor instead.
func (*RootStore) Descriptor() ([]byte, []int) {
	return file_root_store_proto_rawDescGZIP(), []int{3}
}

func (x *RootStore) GetTrustAnchors() []*TrustAnchor {
	if x != nil {
		return x.TrustAnchors
	}
	return nil
}

func (x *RootStore) GetVersionMajor() int64 {
	if x != nil {
		return x.VersionMajor
	}
	return 0
}

func (x *RootStore) GetAdditionalCerts() []*TrustAnchor {
	if x != nil {
		return x.AdditionalCerts
	}
	return nil
}

func (x *RootStore) GetMtcAnchors() []*MtcAnchor {
	if x != nil {
		return x.MtcAnchors
	}
	return nil
}

type TrustAnchorIdRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The base_id is a relative OID in DER representation which, when a
	// landmark number is appended, specifies a Trust Anchor ID for this
	// signatureless MTC.
	BaseId []byte `protobuf:"bytes,1,opt,name=base_id,json=baseId,proto3,oneof" json:"base_id,omitempty"`
	// The minimum supported landmark number.
	MinActiveLandmarkInclusive *uint64 `protobuf:"varint,2,opt,name=min_active_landmark_inclusive,json=minActiveLandmarkInclusive,proto3,oneof" json:"min_active_landmark_inclusive,omitempty"`
	// The maximum supported landmark number, inclusive.
	LastLandmarkInclusive *uint64 `protobuf:"varint,3,opt,name=last_landmark_inclusive,json=lastLandmarkInclusive,proto3,oneof" json:"last_landmark_inclusive,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TrustAnchorIdRange) Reset() {
	*x = TrustAnchorIdRange{}
	mi := &file_root_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrustAnchorIdRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrustAnchorIdRange) ProtoMessage() {}

func (x *TrustAnchorIdRange) ProtoReflect() protoreflect.Message {
	mi := &file_root_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrustAnchorIdRange.ProtoReflect.Descriptor instead.
func (*TrustAnchorIdRange) Descriptor() ([]byte, []int) {
	return file_root_store_proto_rawDescGZIP(), []int{4}
}

func (x *TrustAnchorIdRange) GetBaseId() []byte {
	if x != nil {
		return x.BaseId
	}
	return nil
}

func (x *TrustAnchorIdRange) GetMinActiveLandmarkInclusive() uint64 {
	if x != nil && x.MinActiveLandmarkInclusive != nil {
		return *x.MinActiveLandmarkInclusive
	}
	return 0
}

func (x *TrustAnchorIdRange) GetLastLandmarkInclusive() uint64 {
	if x != nil && x.LastLandmarkInclusive != nil {
		return *x.LastLandmarkInclusive
	}
	return 0
}

type MtcSubTree struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The start index of the range covered by this subtree.
	StartInclusive *uint64 `protobuf:"varint,1,opt,name=start_inclusive,json=startInclusive,proto3,oneof" json:"start_inclusive,omitempty"`
	// The end index, exclusive, of the range covered by this subtree.
	EndExclusive *uint64 `protobuf:"varint,2,opt,name=end_exclusive,json=endExclusive,proto3,oneof" json:"end_exclusive,omitempty"`
	// The merkle tree hash for this subtree.
	Hash          []byte `protobuf:"bytes,3,opt,name=hash,proto3,oneof" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MtcSubTree) Reset() {
	*x = MtcSubTree{}
	mi := &file_root_store_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MtcSubTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtcSubTree) ProtoMessage() {}

func (x *MtcSubTree) ProtoReflect() protoreflect.Message {
	mi := &file_root_store_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtcSubTree.ProtoReflect.Descriptor instead.
func (*MtcSubTree) Descriptor() ([]byte, []int) {
	return file_root_store_proto_rawDescGZIP(), []int{5}
}

func (x *MtcSubTree) GetStartInclusive() uint64 {
	if x != nil && x.StartInclusive != nil {
		return *x.StartInclusive
	}
	return 0
}

func (x *MtcSubTree) GetEndExclusive() uint64 {
	if x != nil && x.EndExclusive != nil {
		return *x.EndExclusive
	}
	return 0
}

func (x *MtcSubTree) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type MtcIndexRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The start index of the range.
	StartInclusive *uint64 `protobuf:"varint,1,opt,name=start_inclusive,json=startInclusive,proto3,oneof" json:"start_inclusive,omitempty"`
	// The end index, exclusive, of the range.
	EndExclusive  *uint64 `protobuf:"varint,2,opt,name=end_exclusive,json=endExclusive,proto3,oneof" json:"end_exclusive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MtcIndexRange) Reset() {
	*x = MtcIndexRange{}
	mi := &file_root_store_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MtcIndexRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtcIndexRange) ProtoMessage() {}

func (x *MtcIndexRange) ProtoReflect() protoreflect.Message {
	mi := &file_root_store_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtcIndexRange.ProtoReflect.Descriptor instead.
func (*MtcIndexRange) Descriptor() ([]byte, []int) {
	return file_root_store_proto_rawDescGZIP(), []int{6}
}

func (x *MtcIndexRange) GetStartInclusive() uint64 {
	if x != nil && x.StartInclusive != nil {
		return *x.StartInclusive
	}
	return 0
}

func (x *MtcIndexRange) GetEndExclusive() uint64 {
	if x != nil && x.EndExclusive != nil {
		return *x.EndExclusive
	}
	return 0
}

type MtcAnchorData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The log id is a trust anchor id in binary representation. This must match
	// the `log_id` for an MtcAnchor in the root store, or this MtcAnchorData
	// will be ignored. (It is not an error for this to occur in practice, since
	// the MtcMetadata and ChromeRootStoreData are updated separately.)
	LogId []byte `protobuf:"bytes,1,opt,name=log_id,json=logId,proto3,oneof" json:"log_id,omitempty"`
	// The range of landmark numbers corresponding to `trusted_subtrees`, along
	// with the base_id, sufficient for constructing the Trust Anchor ID(s) for
	// negotiating the use of signatureless certificates.
	TrustedLandmarkIdsRange *TrustAnchorIdRange `protobuf:"bytes,2,opt,name=trusted_landmark_ids_range,json=trustedLandmarkIdsRange,proto3,oneof" json:"trusted_landmark_ids_range,omitempty"`
	// Trusted subtrees that can be used for signatureless Merkle Tree
	// certificate verification. Presence in this list implies that relevant root
	// store policies have been already been checked offline for all certificates
	// covered by each subtree.
	TrustedSubtrees []*MtcSubTree `protobuf:"bytes,3,rep,name=trusted_subtrees,json=trustedSubtrees,proto3" json:"trusted_subtrees,omitempty"`
	// Ranges of Merkle Tree Certificate indices which are revoked.
	RevokedIndices []*MtcIndexRange `protobuf:"bytes,4,rep,name=revoked_indices,json=revokedIndices,proto3" json:"revoked_indices,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MtcAnchorData) Reset() {
	*x = MtcAnchorData{}
	mi := &file_root_store_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MtcAnchorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtcAnchorData) ProtoMessage() {}

func (x *MtcAnchorData) ProtoReflect() protoreflect.Message {
	mi := &file_root_store_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtcAnchorData.ProtoReflect.Descriptor instead.
func (*MtcAnchorData) Descriptor() ([]byte, []int) {
	return file_root_store_proto_rawDescGZIP(), []int{7}
}

func (x *MtcAnchorData) GetLogId() []byte {
	if x != nil {
		return x.LogId
	}
	return nil
}

func (x *MtcAnchorData) GetTrustedLandmarkIdsRange() *TrustAnchorIdRange {
	if x != nil {
		return x.TrustedLandmarkIdsRange
	}
	return nil
}

func (x *MtcAnchorData) GetTrustedSubtrees() []*MtcSubTree {
	if x != nil {
		return x.TrustedSubtrees
	}
	return nil
}

func (x *MtcAnchorData) GetRevokedIndices() []*MtcIndexRange {
	if x != nil {
		return x.RevokedIndices
	}
	return nil
}

type MtcMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The time this data was generated, in seconds since the unix epoch.
	UpdateTimeSeconds *int64 `protobuf:"varint,1,opt,name=update_time_seconds,json=updateTimeSeconds,proto3,oneof" json:"update_time_seconds,omitempty"`
	// Metadata for each of the supported MTC anchors.
	MtcAnchorData []*MtcAnchorData `protobuf:"bytes,2,rep,name=mtc_anchor_data,json=mtcAnchorData,proto3" json:"mtc_anchor_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MtcMetadata) Reset() {
	*x = MtcMetadata{}
	mi := &file_root_store_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MtcMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MtcMetadata) ProtoMessage() {}

func (x *MtcMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_root_store_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MtcMetadata.ProtoReflect.Descriptor instead.
func (*MtcMetadata) Descriptor() ([]byte, []int) {
	return file_root_store_proto_rawDescGZIP(), []int{8}
}

func (x *MtcMetadata) GetUpdateTimeSeconds() int64 {
	if x != nil && x.UpdateTimeSeconds != nil {
		return *x.UpdateTimeSeconds
	}
	return 0
}

func (x *MtcMetadata) GetMtcAnchorData() []*MtcAnchorData {
	if x != nil {
		return x.MtcAnchorData
	}
	return nil
}

var File_root_store_proto protoreflect.FileDescriptor

const file_root_store_proto_rawDesc = "" +
	"\n" +
	"\x10root_store.proto\x12\x11chrome_root_store\"\xe0\x02\n" +
	"\rConstraintSet\x12.\n" +
	"\x11sct_not_after_sec\x18\x01 \x01(\x03H\x00R\x0esctNotAfterSec\x88\x01\x01\x12.\n" +
	"\x11sct_all_after_sec\x18\x02 \x01(\x03H\x01R\x0esctAllAfterSec\x88\x01\x01\x12$\n" +
	"\vmin_version\x18\x03 \x01(\tH\x02R\n" +
	"minVersion\x88\x01\x01\x127\n" +
	"\x15max_version_exclusive\x18\x04 \x01(\tH\x03R\x13maxVersionExclusive\x88\x01\x01\x12.\n" +
	"\x13permitted_dns_names\x18\x05 \x03(\tR\x11permittedDnsNamesB\x14\n" +
	"\x12_sct_not_after_secB\x14\n" +
	"\x12_sct_all_after_secB\x0e\n" +
	"\f_min_versionB\x18\n" +
	"\x16_max_version_exclusiveJ\x04\b\x06\x10\aJ\x04\b\a\x10\b\"\xd6\x04\n" +
	"\vTrustAnchor\x12\x12\n" +
	"\x03der\x18\x01 \x01(\fH\x00R\x03der\x12\x1f\n" +
	"\n" +
	"sha256_hex\x18\x02 \x01(\tH\x00R\tsha256Hex\x12$\n" +
	"\x0eev_policy_oids\x18\x03 \x03(\tR\fevPolicyOids\x12B\n" +
	"\vconstraints\x18\x04 \x03(\v2 .chrome_root_store.ConstraintSetR\vconstraints\x12&\n" +
	"\fdisplay_name\x18\x05 \x01(\tH\x01R\vdisplayName\x88\x01\x01\x12\x17\n" +
	"\x04eutl\x18\x06 \x01(\bH\x02R\x04eutl\x88\x01\x01\x127\n" +
	"\x15enforce_anchor_expiry\x18\b \x01(\bH\x03R\x13enforceAnchorExpiry\x88\x01\x01\x12A\n" +
	"\x1aenforce_anchor_constraints\x18\t \x01(\bH\x04R\x18enforceAnchorConstraints\x88\x01\x01\x12-\n" +
	"\x10tls_trust_anchor\x18\n" +
	" \x01(\bH\x05R\x0etlsTrustAnchor\x88\x01\x01\x12+\n" +
	"\x0ftrust_anchor_id\x18\v \x01(\fH\x06R\rtrustAnchorId\x88\x01\x01B\r\n" +
	"\vcertificateB\x0f\n" +
	"\r_display_nameB\a\n" +
	"\x05_eutlB\x18\n" +
	"\x16_enforce_anchor_expiryB\x1d\n" +
	"\x1b_enforce_anchor_constraintsB\x13\n" +
	"\x11_tls_trust_anchorB\x12\n" +
	"\x10_trust_anchor_idJ\x04\b\a\x10\b\"\xba\x01\n" +
	"\tMtcAnchor\x12\x1a\n" +
	"\x06log_id\x18\x01 \x01(\fH\x00R\x05logId\x88\x01\x01\x12B\n" +
	"\vconstraints\x18\x02 \x03(\v2 .chrome_root_store.ConstraintSetR\vconstraints\x12-\n" +
	"\x10tls_trust_anchor\x18\x03 \x01(\bH\x01R\x0etlsTrustAnchor\x88\x01\x01B\t\n" +
	"\a_log_idB\x13\n" +
	"\x11_tls_trust_anchor\"\xff\x01\n" +
	"\tRootStore\x12C\n" +
	"\rtrust_anchors\x18\x01 \x03(\v2\x1e.chrome_root_store.TrustAnchorR\ftrustAnchors\x12#\n" +
	"\rversion_major\x18\x02 \x01(\x03R\fversionMajor\x12I\n" +
	"\x10additional_certs\x18\x03 \x03(\v2\x1e.chrome_root_store.TrustAnchorR\x0fadditionalCerts\x12=\n" +
	"\vmtc_anchors\x18\x04 \x03(\v2\x1c.chrome_root_store.MtcAnchorR\n" +
	"mtcAnchors\"\x81\x02\n" +
	"\x12TrustAnchorIdRange\x12\x1c\n" +
	"\abase_id\x18\x01 \x01(\fH\x00R\x06baseId\x88\x01\x01\x12F\n" +
	"\x1dmin_active_landmark_inclusive\x18\x02 \x01(\x04H\x01R\x1aminActiveLandmarkInclusive\x88\x01\x01\x12;\n" +
	"\x17last_landmark_inclusive\x18\x03 \x01(\x04H\x02R\x15lastLandmarkInclusive\x88\x01\x01B\n" +
	"\n" +
	"\b_base_idB \n" +
	"\x1e_min_active_landmark_inclusiveB\x1a\n" +
	"\x18_last_landmark_inclusive\"\xac\x01\n" +
	"\n" +
	"MtcSubTree\x12,\n" +
	"\x0fstart_inclusive\x18\x01 \x01(\x04H\x00R\x0estartInclusive\x88\x01\x01\x12(\n" +
	"\rend_exclusive\x18\x02 \x01(\x04H\x01R\fendExclusive\x88\x01\x01\x12\x17\n" +
	"\x04hash\x18\x03 \x01(\fH\x02R\x04hash\x88\x01\x01B\x12\n" +
	"\x10_start_inclusiveB\x10\n" +
	"\x0e_end_exclusiveB\a\n" +
	"\x05_hash\"\x8d\x01\n" +
	"\rMtcIndexRange\x12,\n" +
	"\x0fstart_inclusive\x18\x01 \x01(\x04H\x00R\x0estartInclusive\x88\x01\x01\x12(\n" +
	"\rend_exclusive\x18\x02 \x01(\x04H\x01R\fendExclusive\x88\x01\x01B\x12\n" +
	"\x10_start_inclusiveB\x10\n" +
	"\x0e_end_exclusive\"\xd3\x02\n" +
	"\rMtcAnchorData\x12\x1a\n" +
	"\x06log_id\x18\x01 \x01(\fH\x00R\x05logId\x88\x01\x01\x12g\n" +
	"\x1atrusted_landmark_ids_range\x18\x02 \x01(\v2%.chrome_root_store.TrustAnchorIdRangeH\x01R\x17trustedLandmarkIdsRange\x88\x01\x01\x12H\n" +
	"\x10trusted_subtrees\x18\x03 \x03(\v2\x1d.chrome_root_store.MtcSubTreeR\x0ftrustedSubtrees\x12I\n" +
	"\x0frevoked_indices\x18\x04 \x03(\v2 .chrome_root_store.MtcIndexRangeR\x0erevokedIndicesB\t\n" +
	"\a_log_idB\x1d\n" +
	"\x1b_trusted_landmark_ids_range\"\xa4\x01\n" +
	"\vMtcMetadata\x123\n" +
	"\x13update_time_seconds\x18\x01 \x01(\x03H\x00R\x11updateTimeSeconds\x88\x01\x01\x12H\n" +
	"\x0fmtc_anchor_data\x18\x02 \x03(\v2 .chrome_root_store.MtcAnchorDataR\rmtcAnchorDataB\x16\n" +
	"\x14_update_time_secondsb\x06proto3"

var (
	file_root_store_proto_rawDescOnce sync.Once
	file_root_store_proto_rawDescData []byte
)

func file_root_store_proto_rawDescGZIP() []byte {
	file_root_store_proto_rawDescOnce.Do(func() {
		file_root_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_root_store_proto_rawDesc), len(file_root_store_proto_rawDesc)))
	})
	return file_root_store_proto_rawDescData
}

var file_root_store_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_root_store_proto_goTypes = []any{
	(*ConstraintSet)(nil),      // 0: chrome_root_store.ConstraintSet
	(*TrustAnchor)(nil),        // 1: chrome_root_store.TrustAnchor
	(*MtcAnchor)(nil),          // 2: chrome_root_store.MtcAnchor
	(*RootStore)(nil),          // 3: chrome_root_store.RootStore
	(*TrustAnchorIdRange)(nil), // 4: chrome_root_store.TrustAnchorIdRange
	(*MtcSubTree)(nil),         // 5: chrome_root_store.MtcSubTree
	(*MtcIndexRange)(nil),      // 6: chrome_root_store.MtcIndexRange
	(*MtcAnchorData)(nil),      // 7: chrome_root_store.MtcAnchorData
	(*MtcMetadata)(nil),        // 8: chrome_root_store.MtcMetadata
}
var file_root_store_proto_depIdxs = []int32{
	0, // 0: chrome_root_store.TrustAnchor.constraints:type_name -> chrome_root_store.ConstraintSet
	0, // 1: chrome_root_store.MtcAnchor.constraints:type_name -> chrome_root_store.ConstraintSet
	1, // 2: chrome_root_store.RootStore.trust_anchors:type_name -> chrome_root_store.TrustAnchor
	1, // 3: chrome_root_store.RootStore.additional_certs:type_name -> chrome_root_store.TrustAnchor
	2, // 4: chrome_root_store.RootStore.mtc_anchors:type_name -> chrome_root_store.MtcAnchor
	4, // 5: chrome_root_store.MtcAnchorData.trusted_landmark_ids_range:type_name -> chrome_root_store.TrustAnchorIdRange
	5, // 6: chrome_root_store.MtcAnchorData.trusted_subtrees:type_name -> chrome_root_store.MtcSubTree
	6, // 7: chrome_root_store.MtcAnchorData.revoked_indices:type_name -> chrome_root_store.MtcIndexRange
	7, // 8: chrome_root_store.MtcMetadata.mtc_anchor_data:type_name -> chrome_root_store.MtcAnchorData
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_root_store_proto_init() }
func file_root_store_proto_init() {
	if File_root_store_proto != nil {
		return
	}
	file_root_store_proto_msgTypes[0].OneofWrappers = []any{}
	file_root_store_proto_msgTypes[1].OneofWrappers = []any{
		(*TrustAnchor_Der)(nil),
		(*TrustAnchor_Sha256Hex)(nil),
	}
	file_root_store_proto_msgTypes[2].OneofWrappers = []any{}
	file_root_store_proto_msgTypes[4].OneofWrappers = []any{}
	file_root_store_proto_msgTypes[5].OneofWrappers = []any{}
	file_root_store_proto_msgTypes[6].OneofWrappers = []any{}
	file_root_store_proto_msgTypes[7].OneofWrappers = []any{}
	file_root_store_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_root_store_proto_rawDesc), len(file_root_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_root_store_proto_goTypes,
		DependencyIndexes: file_root_store_proto_depIdxs,
		MessageInfos:      file_root_store_proto_msgTypes,
	}.Build()
	File_root_store_proto = out.File
	file_root_store_proto_goTypes = nil
	file_root_store_proto_depIdxs = nil
}
